terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
      version = "2.9.0"
    }
  }
}

provider "proxmox" {
  pm_api_url = "https://proxmox.linuxgamer.online:8006/api2/json"
  pm_user    = "root@pam"
  pm_password = "q1w2e3r4"
  pm_tls_insecure = true
}

resource "proxmox_lxc" "web_server" {
  target_node = "proxmox"
  hostname     = "web-server"
  ostemplate   = "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
  password     = "your-password"
  unprivileged = true
  ssh_public_keys = <<EOT
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyYxAwMxFi3B6DA1zfRBXNvghZumrvkV75zdqKa+E7co0P5QCU9wsL30lXyUmJszIDl+FCYuWN1lDj6Uy7/SNXUj2C05ePnhphJGqsyLztWYQGlGtvreI9Z0qujrBCtKq9pI9cvH6mRpbAKQyi5JG8gTQRkiMnPRbDFWO6iL2EMoP/a+L8/mS7I/b4jA24oYxs/rBf2pUP7errn7SD/3Yw8KOeplkPrtU/rkvSUAxQjOmcLncjkgzhe+yClCMcD2naKNqkQu6Pg+BtzOoM79D8qQfVWdf++f1L7jMDsPJULvky0wf4zMQVEyBeni6OsW0hjSgV+lmAYhyjxkHAEKfXchsL7KWopf05YJEnQCmLo6DHld3xgHfmkp2coz016hGBk5qs0LAvQilKQN97GCf4jYN237OUWeKzQpZuTRjmnNYODL/MaNj7qH4vSIkAZnKMysNF1yCHjSF6EvyNJCHBDkJNwOQWOf+8l7CJBJyuN6KWA7fRvVuFzyGWZ7T9KitPDym3qt7G/xL/S5okBk47Ed2s1caeU6bTxsE83Wlv/g97BSR6WC9lzQYBXieaRdiUSPtWzlX+3v88rdlhTmZ3Dy4I12CJ02ErIWNovhzD/6khqLLJ9LfLmGqkxMkLm5g0+PW9ueMe8IKNkegqHFVTCxugwfG3f7bzewY5xwe6rw== Generated By Termius
  EOT
  start        = true
  cores        = 1
  memory       = 512
  swap         = 512
  network {
    name   = "eth0"
    bridge = "vmbr0"
    ip     = "10.69.69.37/24"
    gw = "10.69.69.1"
  }
  rootfs    {
    storage = "local-lvm"
    size = "10G"
  }
}